### ISSUE TITLE
Add web-push-notification feature

### ISSUE THREAD

**Issue by Bshah88** [hagopj13/node-express-mongoose-boilerplate#17] opened 2020-06-16 14:51 UTC
Push notification is a need of every developer. It will be helpful if you can add this feature in your boilerplate. Thanks in advance.

**Comment by hagopj13** [comment] 2020-06-21 18:35
Possible duplicate of #15 
Can you please check and close this one if that is the case?

**Closed** 2020-06-22 05:18 UTC
